# Generated by Django 4.1.5 on 2023-05-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecoapp", "0013_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
