# Generated by Django 4.1.5 on 2023-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoapp", "0014_delete_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="surname",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
    ]
